### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by vorg** [GeometryCollective/geometry-processing-js#1]
Is publishing to npm planned in the future?

**Comment by Erkaman** [comment]
Yeah, I too want this. Having to include this library through <script> tags like in the demos would be really painful IMO. Using modules instead would be so much better.

**Comment by r03ert0** [comment]
hey!
I've been trying to use the code through node, but I'm not there yet... have you guys made any progress?
For some classes, like `MeshIO`, adding a `module.exports = MeshIO;` line at the end makes it possible to required them like `var MeshIO = require('./geometry-processing-js/utils/meshio.js');`. But it's still not working : (

**Comment by rohan-sawhney** [comment]
@r03ert0 [linear-algebra-js](https://github.com/rohan-sawhney/linear-algebra-js) now has node support. I'll add it here as well in a few days.

**Comment by r03ert0** [comment]
Using @rohan-sawhney's version of linear-algebra-js I was able to run the geodesic distance project using node \o/ !!

**Comment by marlinilram** [comment]
@r03ert0 Hi, can you share the steps to run it on a node server? Thank you!

**Comment by Alzy** [comment]
> Using @rohan-sawhney's version of linear-algebra-js I was able to run the geodesic distance project using node \o/ !!

were you able to do this on the browser?

**Comment by r03ert0** [comment]
yes! in the browser. Here's the code:
[Archive.zip](https://github.com/user-attachments/files/16442845/Archive.zip)
it doesn't do much besides computing geodesic distance for one vertex. Share alike if you add some visualisation!
