### ISSUE TITLE
In the heat method, what would be the most efficient way of making a matrix of distances for all vertices?

### ISSUE THREAD

**Issue by r03ert0** [GeometryCollective/geometry-processing-js#2]
In the heat method, what would be the most efficient way of making a matrix of distances for all vertices?

Something about prefactoring is mentioned in @keenancrane's video http://www.cs.cmu.edu/~kmcrane/Projects/HeatMethod/, but I don't really see how to do that in the current `heat-method.js` code...

**Comment by rohan-sawhney** [comment]
The matrix factorization routines (such as the Cholesky, LU and QR) in this framework compute the pre factorization once and automatically reuse it in subsequent calls to the solver. This is the case with the `heat-method.js` code too, the pre factorization for the flow and laplace matrix is only computed the first time you call the `compute` method for any source vertex. For every subsequent vertex that is used as the sourced, the prefactorization of these matrices is reused. The amortized cost of computing a matrix of distances in this fashion is O(n^2).

**Comment by r03ert0** [comment]
aah! that's why `heatMethod.A` and `heatMethod.F` are not deleted in `memoryManager.deleteExcept([phi, delta, heatMethod.A, heatMethod.F]);`

**Comment by r03ert0** [comment]
This is what I'm using to compute the distance matrix for all vertices. Does it look reasonable?

```
function computeDistanceMatrix() {
    let N = mesh.vertices.length;
    let M = new Float32Array(N*N);
    let i, j;
    let dist;
    for(i=0;i<N-1;i++) {
        // set source vertex
        delta.set(1, i, 0);

        // compute distance
        phi = delta.sum() > 0 ? heatMethod.compute(delta) : undefined;
        for(j=i+1;j<N;j++) {
            dist = phi.get(j);
            M[j*N + i] = dist;
            M[i*N + j] = dist;
        }

        // cleanup
        memoryManager.deleteExcept([phi, delta, heatMethod.A, heatMethod.F]);

        // clean source vertex
        delta.set(0, i, 0);
    }
    return M;
}

```
