### ISSUE TITLE
How to traverse the boundary loop in counterclockwise order?

### ISSUE THREAD

**Issue by IsaacGuan** [GeometryCollective/geometry-processing-js#3]
For traversing all the vertices on the boundary, I can use Mesh.boundaries to find out all the boundary loops contained in this mesh which are represented by "imaginary" faces, and then use Face.adjacentVertices() or Face.adjacentHalfedges() to iterate over the the vertices/halfedges of a boundary loop. But I find that the sequence of the items in these iterators is not in CCW order. How can I traverse the boundary loop in counterclockwise order?

**Comment by rohan-sawhney** [comment]
The current iterators traverse interior elements in CCW order and boundary elements in CW order. You could do one of two things: 

1) Manually traverse the boundary as follows:
```
let he = face.halfedge; // face is "imaginary"
do {
    let v = he.vertex;
    // do something with v

    he = he.prev;
} while (he !== face.halfedge);

```
2) Define new Face*Iterator classes and replace [this line](https://github.com/GeometryCollective/geometry-processing-js/blob/314d271403d01159f4eb08b30786afd687c759a4/core/face.js#L135) with:
```
this.current = this.current.prev;
```

**Comment by IsaacGuan** [comment]
Thank you for the quick reply! Now I find I asked a really dump question.
I am implementing tutte embedding using this library, so I just fixed the boundary vertices in clockwise order instead of counterclockwise, and it is getting good result.
Thank you very much!

**Comment by rohan-sawhney** [comment]
I added a flag to use the iterators in CCW or CW order.
