### ISSUE TITLE
Dense matrix inversion

### ISSUE THREAD

**Issue by domparise** [GeometryCollective/geometry-processing-js#4]
Hello, great library, thank you!

Is there a means to perform dense matrix inversion of a square matrix?

Is the asm translation of linear-algebra complete in the full translation of eigen? If so, how can one access these underlying components like inverse() function.

**Comment by rohan-sawhney** [comment]
@domparise not all features of eigen have been converted to asm, mostly because it requires wrapping a lot of functions both on the C/C++ and Javascript side. However, I do plan to wrap more common things like dense matrix factorizations, determinants, eigenvalues/vectors and SVD that are not currently present in the library.

**Comment by domparise** [comment]
@rohan-sawhney good to know, thank you. Using Eigen with asm was something I had thought about doing a little over a year ago, so it was good to hear that someone has gone along and done it.
Is there anything I can do to help? I'm fluent in both javascript and c/c++, but have not yet worked much with emscripten and asm.js. If your timeline is not very aggressive for this, perhaps I could update the system for the functions I need and push it back upstream.
Thanks!

**Comment by rohan-sawhney** [comment]
Hey @domparise, I just uploaded a c++ wrapper for Eigen and some instructions on how to convert to asm.js [here](https://github.com/rohan-sawhney/linear-algebra-js/tree/master/c%2B%2B). Let me know if it works for you :)

**Comment by domparise** [comment]
🙌🙌🙌
Thanks Rohan, we'll take a look into this.
I'll close out this issue and open one in the [linear-algebra-js](https://github.com/rohan-sawhney/linear-algebra-js) if we run into any issues getting Eigen or asm.js to compile.
